name: kids_games_pro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+14

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  lottie: ^3.1.2
  audioplayers: ^6.0.0
  just_audio_background: ^0.0.1-beta.12
  google_mobile_ads: ^5.1.0
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true   # Generate Android icons
  ios: true       # Generate iOS icons
  image_path: "assets/Untitled design.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
